# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.3.0
maven_group = kabopc
archives_base_name = kabo-village-marker
supported_minecraft_versions = 1.8-1.8.1

# Dependencies
minecraft_version = 1.8.1
feather_build = 28
nests_build = 2
loader_version = 0.17.3

osl_version = 0.16.3
